
package br.ba.easyautoproject.view;

import static java.time.Clock.system;

/**
 *
 * @author icaro
 */
public class telaMenu extends javax.swing.JFrame {

    public telaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        cadastroCliente = new javax.swing.JMenuItem();
        cadastroUsuario = new javax.swing.JMenuItem();
        cadastroVeiculo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Cadastros");

        cadastroCliente.setText("Cadastrar Cliente");
        cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClienteActionPerformed(evt);
            }
        });
        jMenu3.add(cadastroCliente);

        cadastroUsuario.setText("Cadastrar Usuário");
        cadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(cadastroUsuario);

        cadastroVeiculo.setText("Cadastrar Veículo");
        jMenu3.add(cadastroVeiculo);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteActionPerformed
        new telaCadastroCliente().setVisible(true);
    }//GEN-LAST:event_cadastroClienteActionPerformed

    private void cadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroUsuarioActionPerformed
    
        
        
        if (telaCadastroUsuario3 == null){
            
            try {
                
          telaCadastroUsuario3 = new TelaCadastroUsuario30();                           
           desktopPane.add(telaCadastroUsuario3);
           
           
            } catch (Exception ex){
                
                System.out.println("eroo " + ex.getMessage());
                        
            }
          
        
        }        
        
        
    }//GEN-LAST:event_cadastroUsuarioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     
        if (telaCadastroUsuario3 == null) {

            try {

                telaCadastroUsuario3 = new TelaCadastroUsuario30();
                desktopPane.add(telaCadastroUsuario3);
                telaCadastroUsuario3.setTitle("ranan ");
                
                telaCadastroUsuario3.show();
                
            } catch (Exception ex) {

                System.out.println("erro " + ex.getMessage());

            }

        }
   

        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastroCliente;
    private javax.swing.JMenuItem cadastroUsuario;
    private javax.swing.JMenuItem cadastroVeiculo;
    public static javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

    private telaCadastroUsuario2 _telaCadastroUsuario = null;
   
    private TelaCadastroUsuario30 telaCadastroUsuario3 = null;

}
